<?php
/**
 * An exemple of extending a PMO_Object class
 *
 * This file is part of the PhpMyObject project.
 * 
 * For questions, help, comments, discussion, etc., please join our
 * forum at {@link http://www.developpez.net/forums/forumdisplay.php?f=770} 
 * or our mailing list at {@link http://groups.google.com/group/pmo-dev}.
 *
 * PhpMyProject is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    PhpMyObject
 * @author     Nicolas Boiteux <nicolas_boiteux@yahoo.fr>
 * @link       http://pmo.developpez.com/
 * @since      PhoMyObject v0.14
 * @version    $Revision: $
 * @copyright  Copyright (C) 2007-2008 Nicolas Boiteux 
 * @license    GPLv3 {@link http://www.gnu.org/licenses/gpl}
 * @filesource
 */

/**
 * provides the much needed helloworld() method to those film_actor people
 * who need so much publicity
 *
 * The name of the class is identical to the database table name
 *
 * This example implements a hellworld() method for a PMO_Object based on 
 * the film_actor database table. This class will be intanciated instead
 * of the generic one. 
 *
 * For this to work, you must provide its name to the table_classname
 * property of the PMO_MyTable/PMO_MyTable_film_actor.php file that will
 * get generated by PMO on first instanciation of a PMO_Object for the 
 * table film_actor.
 *
 * @package PhpMyObject
 */
class film_actor extends PMO_MyObject{

   /**
    * emits a huge "Hello World !" to all the World Wide Web media
    */
	public function helloworld(){
		echo('<h1>hello world !</h1>');
	}
	
}

?>
